# Purpose: Creates the container for running the uDataPacketImportProxy software
#          in a Ubuntu container.
# Usage: podman build -t udatapacketimportproxy:latest -f Dockerfile.deb
#        buildah bud -t udatapacketimportproxy:latest -f Dockerfile.deb
FROM ubuntu:24.04
COPY uDataPacketImportProxy-@PROJECT_VERSION@-Linux.tar.gz .
RUN apt-get update &&\
    apt-get upgrade -y &&\
    apt-get autoremove -y &&\
    apt-get autoclean -y &&\
    apt-get -y install bash &&\
    apt-get -y install libcurl4-openssl-dev &&\
    apt-get -y install libtbb-dev &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    tar -xf ./uDataPacketImportProxy-@PROJECT_VERSION@-Linux.tar.gz &&\
    mv ./uDataPacketImportProxy-@PROJECT_VERSION@-Linux/bin/uDataPacketImportProxy /usr/local/bin &&\
    rm -r ./uDataPacketImportProxy-@PROJECT_VERSION@-Linux/ &&\
    rm -r /var/lib/apt/lists/* ./uDataPacketImportProxy-@PROJECT_VERSION@-Linux.tar.gz

RUN useradd -ms /bin/bash us8
USER us8
WORKDIR /home/us8
